name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước checkout mã nguồn từ repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Cấu hình AWS credentials từ Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # Khởi tạo Terraform
      - name: Terraform Init
        run: terraform init

      # Định dạng Terraform
      - name: Terraform Format
        run: terraform fmt -check

      # Lập kế hoạch Terraform
      - name: Terraform Plan
        run: terraform plan

      # Áp dụng Terraform (nếu cần)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
